#!/usr/bin/env bun
/**
 * Generates docs/generated/schema.md from migrations/*.sql.
 *
 * Run: bun run docs:generate:schema
 * Output: docs/generated/schema.md (commit the result)
 *
 * Applies every migration to an in-memory SQLite DB, then introspects
 * sqlite_master so that ALTER TABLE ADD COLUMN changes (e.g. migration 003)
 * and CREATE VIRTUAL TABLE (e.g. FTS5) are reflected accurately.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import Database from "bun:sqlite";

const ROOT = new URL("..", import.meta.url).pathname;
const MIGRATIONS_DIR = join(ROOT, "migrations");
const OUTPUT_FILE = join(ROOT, "docs", "generated", "schema.md");

// FTS5 internal shadow-table suffixes created automatically by SQLite.
// We exclude them from the doc; the virtual table itself is kept.
const FTS_SHADOW_SUFFIXES = ["_data", "_idx", "_content", "_docsize", "_config"];

interface TableEntry {
  name: string;
  sql: string;
  /** Migration that first created this table. */
  createdBy: string;
  /** Migrations that later modified this table via ALTER TABLE (empty if none). */
  modifiedBy: string[];
}

function isFtsShadowTable(name: string, virtualTableNames: Set<string>): boolean {
  for (const suffix of FTS_SHADOW_SUFFIXES) {
    if (name.endsWith(suffix)) {
      const base = name.slice(0, -suffix.length);
      if (virtualTableNames.has(base)) return true;
    }
  }
  return false;
}

function getCurrentSha(): string {
  try {
    const result = Bun.spawnSync(["git", "rev-parse", "--short", "HEAD"], { cwd: ROOT });
    if (result.exitCode === 0) {
      return new TextDecoder().decode(result.stdout).trim();
    }
  } catch {
    // ignore
  }
  return "unknown";
}

async function main() {
  const sha = getCurrentSha();
  const date = new Date().toISOString().slice(0, 10);

  const files = (await readdir(MIGRATIONS_DIR))
    .filter((f) => f.endsWith(".sql"))
    .sort();

  const db = new Database(":memory:");
  // Track which migration first introduced each table name.
  const tableCreatedBy = new Map<string, string>();
  // Track migrations that later modified a table via ALTER TABLE (ordered).
  const tableModifiedBy = new Map<string, string[]>();

  for (const file of files) {
    type Row = { name: string; sql: string };
    const beforeRows = new Map(
      (db.query("SELECT name, sql FROM sqlite_master WHERE type='table'").all() as Row[]).map(
        (r) => [r.name, r.sql] as [string, string],
      ),
    );

    const content = await readFile(join(MIGRATIONS_DIR, file), "utf8");
    db.exec(content);

    const afterRows = db
      .query("SELECT name, sql FROM sqlite_master WHERE type='table'")
      .all() as Row[];

    for (const { name, sql } of afterRows) {
      if (!beforeRows.has(name)) {
        // New table introduced by this migration.
        tableCreatedBy.set(name, file);
      } else if (beforeRows.get(name) !== sql) {
        // Existing table whose stored SQL changed (ALTER TABLE ADD COLUMN).
        const mods = tableModifiedBy.get(name) ?? [];
        mods.push(file);
        tableModifiedBy.set(name, mods);
      }
    }
  }

  // Collect virtual table names for shadow-table filtering.
  const virtualTableNames = new Set(
    (
      db
        .query("SELECT name FROM sqlite_master WHERE type='table' AND sql LIKE 'CREATE VIRTUAL%'")
        .all() as Array<{ name: string }>
    ).map((r) => r.name),
  );

  // All tables in creation order; sqlite_master.sql reflects the final schema
  // including any columns added via ALTER TABLE ADD COLUMN.
  const allRows = db
    .query("SELECT name, sql FROM sqlite_master WHERE type='table' ORDER BY rowid")
    .all() as Array<{ name: string; sql: string }>;

  const tables: TableEntry[] = allRows
    .filter((r) => !isFtsShadowTable(r.name, virtualTableNames))
    .map((r) => ({
      name: r.name,
      sql: r.sql,
      createdBy: tableCreatedBy.get(r.name) ?? "unknown",
      modifiedBy: tableModifiedBy.get(r.name) ?? [],
    }));

  const lines: string[] = [
    "# DB Schema Reference",
    "",
    `> Last verified against code: ${sha} (${date})`,
    ">",
    "> **Do not edit this file by hand.** Regenerate with `bun run docs:generate:schema`.",
    "> Source: `migrations/*.sql`. If this file looks wrong, fix the migration, not this file.",
    "",
    `${tables.length} tables across ${files.length} migrations.`,
    "",
    "## Tables",
    "",
  ];

  for (const table of tables) {
    lines.push(`### \`${table.name}\``);
    lines.push("");
    const provenance = [`\`migrations/${table.createdBy}\``];
    if (table.modifiedBy.length > 0) {
      provenance.push(...table.modifiedBy.map((m) => `\`migrations/${m}\``));
      lines.push(`_Created in ${provenance[0]}; augmented by ${provenance.slice(1).join(", ")}_`);
    } else {
      lines.push(`_Defined in ${provenance[0]}_`);
    }
    lines.push("");
    lines.push("```sql");
    lines.push(table.sql + ";");
    lines.push("```");
    lines.push("");
  }

  await writeFile(OUTPUT_FILE, lines.join("\n"));
  console.log(`Generated ${OUTPUT_FILE} (${tables.length} tables, SHA ${sha})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
