#!/usr/bin/env bun
/**
 * Generates docs/generated/schema.md from migrations/*.sql.
 *
 * Run: bun run docs:generate:schema
 * Output: docs/generated/schema.md (commit the result)
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

const ROOT = new URL("..", import.meta.url).pathname;
const MIGRATIONS_DIR = join(ROOT, "migrations");
const OUTPUT_FILE = join(ROOT, "docs", "generated", "schema.md");

interface TableDef {
  migration: string;
  name: string;
  sql: string;
}

async function extractTables(file: string, content: string): Promise<TableDef[]> {
  const tables: TableDef[] = [];
  // Match CREATE [VIRTUAL] TABLE blocks (multi-line, stops at semicolon)
  const re = /CREATE\s+(?:VIRTUAL\s+)?TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\([^;]+\)\s*(?:USING\s+\w+\([^)]*\))?(?:\s+WITHOUT\s+ROWID)?;/gis;
  let match: RegExpExecArray | null;
  while ((match = re.exec(content)) !== null) {
    tables.push({ migration: file, name: match[1], sql: match[0].trim() });
  }
  return tables;
}

function getCurrentSha(): string {
  try {
    return execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: ROOT })
      .toString()
      .trim();
  } catch {
    return "unknown";
  }
}

async function main() {
  const sha = getCurrentSha();
  const date = new Date().toISOString().slice(0, 10);

  const files = (await readdir(MIGRATIONS_DIR))
    .filter((f) => f.endsWith(".sql"))
    .sort();

  const allTables: TableDef[] = [];
  for (const file of files) {
    const content = await readFile(join(MIGRATIONS_DIR, file), "utf8");
    allTables.push(...(await extractTables(file, content)));
  }

  const lines: string[] = [
    "# DB Schema Reference",
    "",
    `> Last verified against code: ${sha} (${date})`,
    ">",
    "> **Do not edit this file by hand.** Regenerate with `bun run docs:generate:schema`.",
    "> Source: `migrations/*.sql`. If this file looks wrong, fix the migration, not this file.",
    "",
    `${allTables.length} tables across ${files.length} migrations.`,
    "",
    "## Tables",
    "",
  ];

  for (const table of allTables) {
    lines.push(`### \`${table.name}\``);
    lines.push("");
    lines.push(`_Defined in \`migrations/${table.migration}\`_`);
    lines.push("");
    lines.push("```sql");
    lines.push(table.sql);
    lines.push("```");
    lines.push("");
  }

  await writeFile(OUTPUT_FILE, lines.join("\n"));
  console.log(`Generated ${OUTPUT_FILE} (${allTables.length} tables, SHA ${sha})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
